#!/usr/bin/env bash

PATCHES_FOLDER=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)
git fetch als
git m als/android-msm-wahoo-4.4-oreo-m2
git ra
git ap -3 "${PATCHES_FOLDER}/compiler-clang.h.diff"
git ap -3 "${PATCHES_FOLDER}/futex.h.diff"
